# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d742bc6d01f39e8e4b7862f7d1ac73ffcecda75e2e733cd151cb03d1b4f1e67aee8cad9b66015f60d7dbc481cab2d137215fa1b6b9d65df38929ed3e1d357af9

test:
  secret_key_base: 200149261e6d16162d6bef0f116fe1b7eaea97739203070ff23c64cbb98c8774ae3b4bd73aecf933f6372d162aa88135013ee3090af914ec126cc0db4352e08f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
